version: "3"
services:
  nexus:
    image: sonatype/nexus3:3.39.0
    environment:
      VIRTUAL_HOST: ${NEXUS_HOST_NAME}
      VIRTUAL_PORT: ${NEXUS_HOST_PORT}
      LETSENCRYPT_HOST: ${NEXUS_HOST_NAME}
      #LETSENCRYPT_EMAIL: sowousmane4811@gmail.com
      INSTALL4J_ADD_VM_PARAMS: "-Xms2703m -Xmx2703m -XX:MaxDirectMemorySize=1703m"
    networks:
      - default
      - proxy_my-network
    ports:
      - "5000:5000"
    # labels:
    #   # enable traefik
    #   - "traefik.enable=true"
    #   # router
    #   - "traefik.http.routers.${NEXUS_ROUTEUR_NAME}.rule=Host(`${NEXUS_HOST_NAME}`)"
    #   - "traefik.http.routers.${NEXUS_ROUTEUR_NAME}.entrypoints=websecure"
    #   - "traefik.http.routers.${NEXUS_ROUTEUR_NAME}.service=${NEXUS_SERVICE_NAME}"
    #   # certificate SSL HTTPS
    #   - traefik.http.routers.${NEXUS_ROUTEUR_NAME}.tls=true
    #   - traefik.http.routers.${NEXUS_ROUTEUR_NAME}.tls.certresolver=lets-encrypt
    #   # service
    #   - traefik.http.services.${NEXUS_SERVICE_NAME}.loadbalancer.server.port=${NEXUS_HOST_PORT}
    #   - traefik.http.services.${NEXUS_SERVICE_NAME}.loadbalancer.server.scheme=http
    volumes:
      - nexus-data:/nexus-data
networks:
  proxy_my-network:
    external: true

volumes:
  nexus-data:
