global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# Here it's Prometheus itself.
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]
  
  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]
 
  - job_name: "gitea"
    scrape_interval: 5s
    static_configs:
      - targets: ["gitea:3000"]

  - job_name: "fast-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8000"]
