global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# Here it's Prometheus itself.
rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    scrape_interval: 5s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "gitea"
    scrape_interval: 5s
    static_configs:
      - targets: ["gitea:3000"]

  - job_name: "fast-api"
    scrape_interval: 5s
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: "flask-api-SpaceSense"
    scrape_interval: 10s
    static_configs:
      - targets: ["192.168.252.34:5000"]
      
  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - https://spacesense-test.ey.r.appspot.com/
        labels:
          server: "SpaceSense-api-test"
      - targets:
          - https://spacesense-api.ew.r.appspot.com/
        labels:
          server: "SpaceSense-api-prod"
      - targets:
          - https://www.spacesense.ai/
        labels:
          server: "SpaceSense-web-site"
      - targets:
          - https://testtest.spacesense.ai/
        labels:
          server: "SpaceSense-test-error"
      - targets:
          - https://testtest.savoirguinee.com
        labels:
          server: "savoir-guinee"

    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox:9115 #
