version: "3.9"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my-network

  web:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=test.soowcode.local
    networks:
      - my-network
networks:
  my-network:
    external: false
