version: "3.9"
services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - my-network
    logging:
      driver: journald
      options:
        tag: "test-nginx-app-1"

  web:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=test.soowcode.local
    #hostname: "ousmane"
    networks:
      - my-network
    # cap_add:
    #   - ALL
    # cap_drop:
    #   - NET_ADMIN
    #   - SYS_ADMIN
    deploy:
      resources:
        limits:
          memory: 7m
          cpus: '0.1'
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "whoami"
networks:
  my-network:
    external: false
