version: "3.9"
services:
  mysql:
    image: mysql:5.7.36
    hostname: db-mysql
    container_name: db-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root-secret
      - MYSQL_USER=ousmane
      - MYSQL_PASSWORD=ousmane-secret
      - MYSQL_DATABASE=restaurant
    ports:
      - 3306:3306
    networks:
      - default

  adminer:
    depends_on:
      - mysql
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - VIRTUAL_HOST=mysql.soowcode.local
      - VIRTUAL_PORT=8080
    networks:
      - proxy_my-network
      - default

networks:
  proxy_my-network:
    external: true
